name: Android CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and test
        run: |
          cd path/to/your/android/app
          ./gradlew clean build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and sign release APK
        run: |
          cd path/to/your/android/app
          ./gradlew clean assembleRelease

      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          app_token: ${{ secrets.FIREBASE_APP_TOKEN }}
          release_notes: "New release"
          app_file: app/build/outputs/apk/release/app-release.apk
